name: screenwriter_editor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_quill: ^11.1.0
  file_picker: ^9.0.2
  path_provider: ^2.1.2
  flutter_code_editor: ^0.3.2
  highlight: ^0.7.0
  percent_indicator: ^4.2.4
  permission_handler: ^11.4.0
  fl_chart: ^0.70.2
  fast_charts: ^0.2.2
  toastification: ^3.0.2
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  crypto: ^3.0.3
  http: ^1.2.0
  flutter_rust_bridge: 2.10.0
  rust_lib_screenwriter_editor:
    path: rust_builder
  freezed_annotation: ^3.0.0
  # 外部程序打开文件
  open_file: ^3.5.10
  # Microsoft文档预览库
  microsoft_viewer: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  freezed: ^3.0.6
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
