name: screenwriter_editor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_quill: ^11.1.0
  file_picker: ^9.0.2
  path_provider: ^2.1.2
  flutter_code_editor: ^0.3.2
  highlight: ^0.7.0
  percent_indicator: ^4.2.4
  permission_handler: ^11.4.0
  fl_chart: ^0.70.2
  fast_charts: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
